########################################################
#set_property PACKAGE_PIN A8 [get_ports red_led]
#set_property PACKAGE_PIN R17 [get_ports active_h_led]

set_property PACKAGE_PIN D18 [get_ports red_led]
set_property PACKAGE_PIN J17 [get_ports active_h_led]
###########################################################
#set_property PACKAGE_PIN L15 [get_ports active_l_led]


#set_property PACKAGE_PIN A14 [get_ports spare0]
#set_property PACKAGE_PIN F15 [get_ports spare1]


set_property PACKAGE_PIN K2 [get_ports up]

set_property PACKAGE_PIN E3 [get_ports {fn_sw[1]}]
set_property PACKAGE_PIN D4 [get_ports {fn_sw[0]}]
set_property PACKAGE_PIN D3 [get_ports {lcd_data[7]}]
set_property PACKAGE_PIN H1 [get_ports {lcd_data[6]}]
set_property PACKAGE_PIN G1 [get_ports {lcd_data[5]}]
set_property PACKAGE_PIN F1 [get_ports {lcd_data[4]}]
set_property PACKAGE_PIN E1 [get_ports {lcd_data[3]}]
set_property PACKAGE_PIN C1 [get_ports {lcd_data[2]}]
set_property PACKAGE_PIN C2 [get_ports {lcd_data[1]}]
set_property PACKAGE_PIN B1 [get_ports {lcd_data[0]}]
set_property PACKAGE_PIN A1 [get_ports lcd_en]
set_property PACKAGE_PIN B2 [get_ports lcd_rw]
set_property PACKAGE_PIN B3 [get_ports lcd_rs]

set_property PACKAGE_PIN P17 [get_ports Clk_in]
###############################################
#set_property PACKAGE_PIN A13 [get_ports TXD]
#set_property PACKAGE_PIN A11 [get_ports RXD] 
#set_property PACKAGE_PIN K1 [get_ports down]
#set_property PACKAGE_PIN J2 [get_ports s100]

set_property PACKAGE_PIN M6 [get_ports TXD]
set_property PACKAGE_PIN L6 [get_ports RXD]
set_property PACKAGE_PIN J14 [get_ports down]
set_property PACKAGE_PIN F18 [get_ports s100] 

set_property PACKAGE_PIN A13 [get_ports ser_out]
set_property IOSTANDARD LVCMOS33 [get_ports ser_out]
set_property PACKAGE_PIN A11 [get_ports ser_in]
set_property IOSTANDARD LVCMOS33 [get_ports ser_in]
set_property PACKAGE_PIN K1 [get_ports sw_0]
set_property IOSTANDARD LVCMOS33 [get_ports sw_0]
set_property PACKAGE_PIN J2 [get_ports sw_1]
set_property IOSTANDARD LVCMOS33 [get_ports sw_1]
##############################################    
set_property PACKAGE_PIN C15 [get_ports RXD_O]
set_property PACKAGE_PIN D15 [get_ports RXD_IsO]
        
set_property PACKAGE_PIN B11 [get_ports T2EX]
set_property PACKAGE_PIN R10 [get_ports T2]
set_property PACKAGE_PIN R13 [get_ports T1]
set_property PACKAGE_PIN R12 [get_ports T0]
set_property PACKAGE_PIN L18 [get_ports INT1]
set_property PACKAGE_PIN M13 [get_ports INT0]
set_property PACKAGE_PIN J3 [get_ports step]
set_property PACKAGE_PIN F3 [get_ports start]  
set_property PACKAGE_PIN D5 [get_ports reset_main]
set_property PACKAGE_PIN F4 [get_ports stop]   

set_property PACKAGE_PIN U12 [get_ports {P0[7]}]
set_property PACKAGE_PIN V12 [get_ports {P0[6]}]
set_property PACKAGE_PIN N14 [get_ports {P0[5]}]
set_property PACKAGE_PIN P14 [get_ports {P0[4]}]
set_property PACKAGE_PIN T14 [get_ports {P0[3]}]
set_property PACKAGE_PIN T15 [get_ports {P0[2]}]
set_property PACKAGE_PIN P15 [get_ports {P0[1]}]
set_property PACKAGE_PIN R15 [get_ports {P0[0]}]

set_property PACKAGE_PIN T11 [get_ports {P1[7]}]
set_property PACKAGE_PIN U11 [get_ports {P1[6]}]
set_property PACKAGE_PIN T10 [get_ports {P1[5]}]
set_property PACKAGE_PIN T9 [get_ports {P1[4]}]
set_property PACKAGE_PIN H6 [get_ports {P1[3]}]
set_property PACKAGE_PIN H5 [get_ports {P1[2]}]

#####################################################
#set_property PACKAGE_PIN J4 [get_ports {P1[1]}]
#set_property PACKAGE_PIN V11 [get_ports {P1[0]}]

set_property PACKAGE_PIN A8 [get_ports {P1[1]}]
set_property PACKAGE_PIN R17 [get_ports {P1[0]}]
#####################################################
set_property PACKAGE_PIN A3 [get_ports {P2[0]}]
set_property PACKAGE_PIN E5 [get_ports {P2[1]}]
set_property PACKAGE_PIN E6 [get_ports {P2[2]}]
set_property PACKAGE_PIN M17 [get_ports {P2[3]}]
set_property PACKAGE_PIN M16 [get_ports {P2[4]}]
set_property PACKAGE_PIN N16 [get_ports {P2[5]}]
set_property PACKAGE_PIN N15 [get_ports {P2[6]}]
set_property PACKAGE_PIN V10 [get_ports {P2[7]}]

set_property PACKAGE_PIN M18 [get_ports {P3[0]}]
set_property PACKAGE_PIN R16 [get_ports {P3[1]}]
set_property PACKAGE_PIN J5 [get_ports {P3[2]}]
set_property PACKAGE_PIN B7 [get_ports {P3[3]}]
set_property PACKAGE_PIN B6 [get_ports {P3[4]}]
set_property PACKAGE_PIN A6 [get_ports {P3[5]}]
set_property PACKAGE_PIN A5 [get_ports {P3[6]}]
set_property PACKAGE_PIN A4 [get_ports {P3[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports red_led]
set_property IOSTANDARD LVCMOS33 [get_ports active_h_led]
#set_property IOSTANDARD LVCMOS33 [get_ports active_l_led]


#set_property IOSTANDARD LVCMOS33 [get_ports spare0]
#set_property IOSTANDARD LVCMOS33 [get_ports spare1]

set_property IOSTANDARD LVCMOS33 [get_ports {fn_sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fn_sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports s100]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_en]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rw]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rs]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {P0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {P2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P2[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {P3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P3[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P3[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P3[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P3[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P3[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P3[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {P3[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports Clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports INT0]
#set_property DIRECTION IN [get_ports INT1]
set_property IOSTANDARD LVCMOS33 [get_ports INT1]
#set_property DIRECTION IN [get_ports T0]
set_property IOSTANDARD LVCMOS33 [get_ports T0]
#set_property DIRECTION IN [get_ports T1]
set_property IOSTANDARD LVCMOS33 [get_ports T1]
#set_property DIRECTION IN [get_ports T2]
set_property IOSTANDARD LVCMOS33 [get_ports T2]
#set_property DIRECTION IN [get_ports T2EX]
set_property IOSTANDARD LVCMOS33 [get_ports T2EX]
#set_property DIRECTION IN [get_ports RXD]
set_property IOSTANDARD LVCMOS33 [get_ports RXD]
#set_property DIRECTION OUT [get_ports RXD_IsO]
set_property IOSTANDARD LVCMOS33 [get_ports RXD_IsO]
#set_property DRIVE 12 [get_ports RXD_IsO]
#set_property SLEW SLOW [get_ports RXD_IsO]
#set_property DIRECTION OUT [get_ports RXD_O]
set_property IOSTANDARD LVCMOS33 [get_ports RXD_O]

set_property IOSTANDARD LVCMOS33 [get_ports TXD]
set_property IOSTANDARD LVCMOS33 [get_ports step]
set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports reset_main]
set_property IOSTANDARD LVCMOS33 [get_ports stop]

create_clock -period 10.000 -name Clk_in -waveform {0.000 5.000} [get_ports Clk_in]
#create_generated_clock -name core_clk -source [get_ports Clk_in] -divide_by 50000 [get_pins core_clk_reg_n_0_BUFG_inst/O]
#create_generated_clock -name clk -source [get_ports Clk_in] -divide_by 100000 [get_pins clk_reg/Q]
#create_generated_clock -name slow_clk -source [get_ports Clk_in] -divide_by 50000 [get_pins slow_clk_reg/Q]
#set_false_path -from [get_clocks Clk_in] -to [get_clocks slow_clk]
#set_false_path -from [get_clocks Clk_in] -to [get_clocks clk]
#set_false_path -through [get_pins slow_clk_reg/Q]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_MODE SPIx2 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 2 [current_design]


set_property PULLDOWN true [get_ports {P3[0]}]
set_property PULLDOWN true [get_ports {P3[1]}]
set_property PULLDOWN true [get_ports {P3[2]}]
set_property PULLDOWN true [get_ports {P3[3]}]
set_property PULLDOWN true [get_ports {P3[4]}]
set_property PULLDOWN true [get_ports {P3[5]}]
set_property PULLDOWN true [get_ports {P3[6]}]
set_property PULLDOWN true [get_ports {P3[7]}]

set_property PULLDOWN true [get_ports {P2[0]}]
set_property PULLDOWN true [get_ports {P2[1]}]
set_property PULLDOWN true [get_ports {P2[2]}]
set_property PULLDOWN true [get_ports {P2[3]}]
set_property PULLDOWN true [get_ports {P2[4]}]
set_property PULLDOWN true [get_ports {P2[5]}]
set_property PULLDOWN true [get_ports {P2[6]}]
set_property PULLDOWN true [get_ports {P2[7]}]

set_property PULLDOWN true [get_ports {P1[0]}]
set_property PULLDOWN true [get_ports {P1[1]}]
set_property PULLDOWN true [get_ports {P1[2]}]
set_property PULLDOWN true [get_ports {P1[3]}]
set_property PULLDOWN true [get_ports {P1[4]}]
set_property PULLDOWN true [get_ports {P1[5]}]
set_property PULLDOWN true [get_ports {P1[6]}]
set_property PULLDOWN true [get_ports {P1[7]}]

set_property PULLDOWN true [get_ports {P0[0]}]
set_property PULLDOWN true [get_ports {P0[1]}]
set_property PULLDOWN true [get_ports {P0[2]}]
set_property PULLDOWN true [get_ports {P0[3]}]
set_property PULLDOWN true [get_ports {P0[4]}]
set_property PULLDOWN true [get_ports {P0[5]}]
set_property PULLDOWN true [get_ports {P0[6]}]
set_property PULLDOWN true [get_ports {P0[7]}]
