# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/VHDL/Basys 3/Research Project/all_2/all_2.cache/wt} [current_project]
set_property parent.project_path {D:/VHDL/Basys 3/Research Project/all_2/all_2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/VHDL/Basys 3/Research Project/all_2/all_2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51_Pack.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51_ALU.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51_Glue.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51_MD.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51_Port0.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51_Port1.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51_Port2.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51_Port3.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51_RAM.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51_TC01.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51_TC2.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T51_UART.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/new/clk_mux.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/lcd_controller.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/new/mod_sel.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/mux_addrs.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/receiver_1.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/rom_n.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/transmitter_f.vhd}
  {D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/sources_1/imports/Source_code/T8052.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/constrs_1/imports/Constraints_file/TE0711_orig_proj.xdc}}
set_property used_in_implementation false [get_files {{D:/VHDL/Basys 3/Research Project/all_2/all_2.srcs/constrs_1/imports/Constraints_file/TE0711_orig_proj.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top T8052 -part xc7a35tcsg324-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef T8052.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file T8052_utilization_synth.rpt -pb T8052_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
